# настройка подключения к базе данных
spring:
  datasource:
    #ссылка на БД в контейнере
    url: jdbc:postgresql://localhost:5433/students_documents_bd
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:

    hibernate:
      #validate - проверяет наличие таблиц и их колонки
      #update - дополняет но не удаляет
      #create-drop
      ddl-auto: create-drop
    #SQL в логах
    show-sql: true

    properties:
      #Диалект с уточнением базы данных
      dialect: org.hibernate.dialect.PostgreSQLDialect
      #Формат SQL в логах
      format_sql: true


logging:
  level:
    #Для написанного кода логирование максимальное
    com.castles.seudensdocuments.core: TRACE
    #В логах отображаем информацию о обработке спрингом HHTP запросов
    org.springframework.web: DEBUG
    #Отображаем в логах SQL запросы к БД
    org.hibernate.SQL: TRACE
    #В SQL запросах к БД подставляем реальные значения вместо "?"
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    #Отображаем в логах подробно результат мапинга из БД
    org.hibernate.orm.results.bind: TRACE
    #Отображаем в логах ResultSet
    org.hibernate.orm.jdbc.extract: TRACE

